name: KuramaPractice
version: dev
author: tetelie
main: fr.tetelie.practice.Practice
commands:
  practice:
    permission: practice.admin
  arena:
    permission: practice.arena
  inventory:
  build:
    permission: practice.build
  duel:
  accept:
  ping:
  spectate:
    aliases: [spec]
  elo: